[build]
  command = "npm run build"
  publish = "dist/client"

[build.environment]
  NPM_FLAGS = "--include=dev"

[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "development"
