/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as ComplaintRouteImport } from './routes/complaint'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FraudRingsRouteImport } from './routes/fraud-rings'
import { Route as InvestigatorRouteImport } from './routes/investigator'
import { Route as IoDashboardRouteImport } from './routes/io-dashboard'
import { Route as MetricsRouteImport } from './routes/metrics'
import { Route as TimestampAuditRouteImport } from './routes/timestamp-audit'
import { Route as IoComplaintIdRouteImport } from './routes/io-complaint.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplaintRoute = ComplaintRouteImport.update({
  id: '/complaint',
  path: '/complaint',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FraudRingsRoute = FraudRingsRouteImport.update({
  id: '/fraud-rings',
  path: '/fraud-rings',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigatorRoute = InvestigatorRouteImport.update({
  id: '/investigator',
  path: '/investigator',
  getParentRoute: () => rootRouteImport,
} as any)
const IoDashboardRoute = IoDashboardRouteImport.update({
  id: '/io-dashboard',
  path: '/io-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricsRoute = MetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const TimestampAuditRoute = TimestampAuditRouteImport.update({
  id: '/timestamp-audit',
  path: '/timestamp-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const IoComplaintIdRoute = IoComplaintIdRouteImport.update({
  id: '/io-complaint/$id',
  path: '/io-complaint/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/alerts': typeof AlertsRoute
  '/audit': typeof AuditRoute
  '/chat': typeof ChatRoute
  '/complaint': typeof ComplaintRoute
  '/dashboard': typeof DashboardRoute
  '/fraud-rings': typeof FraudRingsRoute
  '/investigator': typeof InvestigatorRoute
  '/io-dashboard': typeof IoDashboardRoute
  '/metrics': typeof MetricsRoute
  '/timestamp-audit': typeof TimestampAuditRoute
  '/io-complaint/$id': typeof IoComplaintIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/alerts': typeof AlertsRoute
  '/audit': typeof AuditRoute
  '/chat': typeof ChatRoute
  '/complaint': typeof ComplaintRoute
  '/dashboard': typeof DashboardRoute
  '/fraud-rings': typeof FraudRingsRoute
  '/investigator': typeof InvestigatorRoute
  '/io-dashboard': typeof IoDashboardRoute
  '/metrics': typeof MetricsRoute
  '/timestamp-audit': typeof TimestampAuditRoute
  '/io-complaint/$id': typeof IoComplaintIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/alerts': typeof AlertsRoute
  '/audit': typeof AuditRoute
  '/chat': typeof ChatRoute
  '/complaint': typeof ComplaintRoute
  '/dashboard': typeof DashboardRoute
  '/fraud-rings': typeof FraudRingsRoute
  '/investigator': typeof InvestigatorRoute
  '/io-dashboard': typeof IoDashboardRoute
  '/metrics': typeof MetricsRoute
  '/timestamp-audit': typeof TimestampAuditRoute
  '/io-complaint/$id': typeof IoComplaintIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/alerts'
    | '/audit'
    | '/chat'
    | '/complaint'
    | '/dashboard'
    | '/fraud-rings'
    | '/investigator'
    | '/io-dashboard'
    | '/metrics'
    | '/timestamp-audit'
    | '/io-complaint/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/alerts'
    | '/audit'
    | '/chat'
    | '/complaint'
    | '/dashboard'
    | '/fraud-rings'
    | '/investigator'
    | '/io-dashboard'
    | '/metrics'
    | '/timestamp-audit'
    | '/io-complaint/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/alerts'
    | '/audit'
    | '/chat'
    | '/complaint'
    | '/dashboard'
    | '/fraud-rings'
    | '/investigator'
    | '/io-dashboard'
    | '/metrics'
    | '/timestamp-audit'
    | '/io-complaint/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AlertsRoute: typeof AlertsRoute
  AuditRoute: typeof AuditRoute
  ChatRoute: typeof ChatRoute
  ComplaintRoute: typeof ComplaintRoute
  DashboardRoute: typeof DashboardRoute
  FraudRingsRoute: typeof FraudRingsRoute
  InvestigatorRoute: typeof InvestigatorRoute
  IoDashboardRoute: typeof IoDashboardRoute
  MetricsRoute: typeof MetricsRoute
  TimestampAuditRoute: typeof TimestampAuditRoute
  IoComplaintIdRoute: typeof IoComplaintIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complaint': {
      id: '/complaint'
      path: '/complaint'
      fullPath: '/complaint'
      preLoaderRoute: typeof ComplaintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fraud-rings': {
      id: '/fraud-rings'
      path: '/fraud-rings'
      fullPath: '/fraud-rings'
      preLoaderRoute: typeof FraudRingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigator': {
      id: '/investigator'
      path: '/investigator'
      fullPath: '/investigator'
      preLoaderRoute: typeof InvestigatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/io-dashboard': {
      id: '/io-dashboard'
      path: '/io-dashboard'
      fullPath: '/io-dashboard'
      preLoaderRoute: typeof IoDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metrics': {
      id: '/metrics'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof MetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timestamp-audit': {
      id: '/timestamp-audit'
      path: '/timestamp-audit'
      fullPath: '/timestamp-audit'
      preLoaderRoute: typeof TimestampAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/io-complaint/$id': {
      id: '/io-complaint/$id'
      path: '/io-complaint/$id'
      fullPath: '/io-complaint/$id'
      preLoaderRoute: typeof IoComplaintIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AlertsRoute: AlertsRoute,
  AuditRoute: AuditRoute,
  ChatRoute: ChatRoute,
  ComplaintRoute: ComplaintRoute,
  DashboardRoute: DashboardRoute,
  FraudRingsRoute: FraudRingsRoute,
  InvestigatorRoute: InvestigatorRoute,
  IoDashboardRoute: IoDashboardRoute,
  MetricsRoute: MetricsRoute,
  TimestampAuditRoute: TimestampAuditRoute,
  IoComplaintIdRoute: IoComplaintIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
